import {test,expect} from "bun:test";
import {availableRescheduleSlots,validateReschedule,rescheduleText,clinicNow,type RescheduleSnapshot} from "./booking-reschedule";
import {resolveAllowedTabs} from "./tab-access";
const now=new Date("2026-10-03T00:00:00Z");
function fixture():RescheduleSnapshot{return {appointment:{id:"a",clinic_id:"c",lead_id:"l",booking_rep_id:"r",patient_name:"Jane Smith",patient_phone:"0400000000",doctor_name:"Debra Best — Hair Regrowth Specialist",appointment_date:"2026-10-06",appointment_time:"09:00",updated_at:"now",outcome:null,disqualified_at:null},clinic:{clinic_name:"Boss Clinic",address:"3/28 Hood St Subiaco WA 6008",city:"Perth",state:"WA",phone:"(08) 9388 2884",min_appointment_gap_mins:0},trading:Array.from({length:7},(_,day_of_week)=>({day_of_week,open_time:"09:00",close_time:"17:00",is_closed:false,consult_duration_mins:15})),blocks:[],busy:[],overrides:[],reminder:{id:"rem",status:"confirmed"}};}
test("own current slot can be reviewed but unchanged booking is rejected",()=>{const s=fixture();expect(availableRescheduleSlots(s,"2026-10-06",now).some(x=>x.time==="09:00")).toBe(true);expect(()=>validateReschedule(s,"2026-10-06","09:00",now)).toThrow("different");});
test("occupied slots, overlap and clinic minimum gap are excluded",()=>{const s=fixture();s.busy=[{appointment_date:"2026-10-06",appointment_time:"10:00"}];s.clinic.min_appointment_gap_mins=15;const times=availableRescheduleSlots(s,"2026-10-06",now).map(x=>x.time);expect(times).not.toContain("09:30");expect(times).not.toContain("10:30");expect(times).toContain("10:45");expect(()=>validateReschedule(s,"2026-10-06","10:00",now)).toThrow("available");});
test("closed days, recurring blocks, holidays and overrides follow shared clinic rules",()=>{const s=fixture();s.clinic.state="NSW";expect(availableRescheduleSlots(s,"2026-10-05",now)).toEqual([]);s.overrides=[{override_date:"2026-10-05",override_type:"open",start_time:"09:00",end_time:"12:00"}];expect(availableRescheduleSlots(s,"2026-10-05",now).length).toBeGreaterThan(0);s.blocks=[{slot_date:null,slot_start:"09:00",slot_end:"10:00",is_recurring:true,recur_day_of_week:1}];expect(availableRescheduleSlots(s,"2026-10-06",now).some(x=>x.time==="09:00")).toBe(false);});
test("past/invalid dates and out-of-hours times are rejected",()=>{for(const [d,t] of [["2026-10-02","10:00"],["2026-02-31","10:00"],["2026-10-06","17:00"],["2026-10-06","9am"]])expect(()=>validateReschedule(fixture(),d,t,now)).toThrow();});
test("same-day past slots are excluded in the existing Sydney timezone",()=>{expect(clinicNow("WA",new Date("2026-10-04T00:00:00Z")).time).toBe("11:00");expect(availableRescheduleSlots(fixture(),"2026-10-03",now).some(x=>x.time<="10:00")).toBe(false);});
test("cancelled, completed and disqualified appointments cannot be moved",()=>{for(const patch of [{outcome:"noshow"},{disqualified_at:"now"}]){const s=fixture();Object.assign(s.appointment,patch);expect(()=>validateReschedule(s,"2026-10-06","11:00",now)).toThrow("active");}const s=fixture();s.reminder!.status="cancelled";expect(()=>validateReschedule(s,"2026-10-06","11:00",now)).toThrow("active");});
test("reschedule text preserves Debra and full Boss contact without titles",()=>{const text=rescheduleText(fixture(),"2026-10-06","11:30");expect(text).toBe("Hi Jane, your hair transplant consultation has been rescheduled to Tuesday 6 October at 11:30 AM with Debra Best at Boss Clinic. Address: 3/28 Hood St Subiaco WA 6008. If you need to reschedule, call Boss Clinic on (08) 9388 2884.");});
test("reps get appointments but cannot acquire a partner-portal tab through overrides",()=>{expect(resolveAllowedTabs("rep",null)).toContain("appointments");expect(resolveAllowedTabs("rep",["appointments","partner_clinics"])).toEqual(["appointments"]);expect(resolveAllowedTabs("admin",[])).toContain("partner_clinics");expect(resolveAllowedTabs("caller",null)).not.toContain("appointments");});
