#!/usr/bin/env bash
# Compiles the 3D map into a static script the page loads at runtime.
set -euo pipefail
cd "$(dirname "$0")/.."
rm -f public/ops/scene.*.js
tmp=$(mktemp)
bun build src/components/numbers-game/scene.entry.ts --target=browser --format=iife --minify --outfile="$tmp" >/dev/null
hash=$(shasum "$tmp" | cut -c1-10)
mv "$tmp" "public/ops/scene.$hash.js"
printf '// Generated by scripts/build-scene.sh. Do not edit.\nexport const SCENE_BUNDLE = "/ops/scene.%s.js";\n' "$hash" > src/components/numbers-game/scene-bundle.ts
echo "public/ops/scene.$hash.js"
