#!/usr/bin/env bash
# Compiles the 3D map (scene-src/) into a static script the page loads at
# runtime. The map's only dependency (three.js) lives in scene-src/package.json,
# so the app's own package.json and build never touch it.
set -euo pipefail
cd "$(dirname "$0")/../scene-src"
bun install --silent
# Typecheck the map itself; errors in files under ../src belong to the app's own checks.
set +e
tsout=$(bunx tsc -p tsconfig.json 2>&1)
set -e
if echo "$tsout" | grep -E '^(scene|entry)\.ts' >/dev/null; then echo "$tsout" | grep -E '^(scene|entry)\.ts'; exit 1; fi
cd ..
rm -f public/ops/scene.*.js
tmp=$(mktemp)
bun build scene-src/entry.ts --target=browser --format=iife --minify --outfile="$tmp" >/dev/null
hash=$(shasum "$tmp" | cut -c1-10)
mv "$tmp" "public/ops/scene.$hash.js"
printf '// Generated by scripts/build-scene.sh. Do not edit.\nexport const SCENE_BUNDLE = "/ops/scene.%s.js";\n' "$hash" > src/components/numbers-game/scene-bundle.ts
echo "public/ops/scene.$hash.js"
