/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClinicPortalRouteImport } from './routes/clinic-portal'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiCoachStreamRouteImport } from './routes/api.coach-stream'
import { Route as DashboardTrainingRouteImport } from './routes/_dashboard.training'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardSentLinksRouteImport } from './routes/_dashboard.sent-links'
import { Route as DashboardSalesCallRouteImport } from './routes/_dashboard.sales-call'
import { Route as DashboardPitchDeckRouteImport } from './routes/_dashboard.pitch-deck'
import { Route as DashboardPartnerClinicsRouteImport } from './routes/_dashboard.partner-clinics'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard.logs'
import { Route as DashboardLeadsRouteImport } from './routes/_dashboard.leads'
import { Route as DashboardLeaderboardRouteImport } from './routes/_dashboard.leaderboard'
import { Route as DashboardInboxRouteImport } from './routes/_dashboard.inbox'
import { Route as DashboardClinicsRouteImport } from './routes/_dashboard.clinics'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardBookedAppointmentsRouteImport } from './routes/_dashboard.booked-appointments'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as DashboardTrainingIndexRouteImport } from './routes/_dashboard.training.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicMetaLeadsRouteImport } from './routes/api.public.meta-leads'
import { Route as DashboardTrainingSalesCallExampleRouteImport } from './routes/_dashboard.training.sales-call-example'
import { Route as DashboardTrainingReadAlongRouteImport } from './routes/_dashboard.training.read-along'
import { Route as DashboardTrainingProductKnowledgeRouteImport } from './routes/_dashboard.training.product-knowledge'
import { Route as DashboardTrainingPracticeCallRouteImport } from './routes/_dashboard.training.practice-call'
import { Route as DashboardTrainingPlatformRouteImport } from './routes/_dashboard.training.platform'
import { Route as DashboardTrainingConsultationVideosRouteImport } from './routes/_dashboard.training.consultation-videos'
import { Route as DashboardTrainingAudienceRouteImport } from './routes/_dashboard.training.audience'
import { Route as DashboardTrainingAiRouteImport } from './routes/_dashboard.training.ai'
import { Route as DashboardTrainingSalesFrameworkIndexRouteImport } from './routes/_dashboard.training.sales-framework.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksStripeDepositRouteImport } from './routes/api.public.hooks.stripe-deposit'
import { Route as ApiPublicHooksReconcileCallDurationsRouteImport } from './routes/api.public.hooks.reconcile-call-durations'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPortalRoute = ClinicPortalRouteImport.update({
  id: '/clinic-portal',
  path: '/clinic-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachStreamRoute = ApiCoachStreamRouteImport.update({
  id: '/api/coach-stream',
  path: '/api/coach-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSentLinksRoute = DashboardSentLinksRouteImport.update({
  id: '/sent-links',
  path: '/sent-links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesCallRoute = DashboardSalesCallRouteImport.update({
  id: '/sales-call',
  path: '/sales-call',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPitchDeckRoute = DashboardPitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPartnerClinicsRoute = DashboardPartnerClinicsRouteImport.update({
  id: '/partner-clinics',
  path: '/partner-clinics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClinicsRoute = DashboardClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookedAppointmentsRoute =
  DashboardBookedAppointmentsRouteImport.update({
    id: '/booked-appointments',
    path: '/booked-appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainingIndexRoute = DashboardTrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTrainingRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaLeadsRoute = ApiPublicMetaLeadsRouteImport.update({
  id: '/api/public/meta-leads',
  path: '/api/public/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTrainingSalesCallExampleRoute =
  DashboardTrainingSalesCallExampleRouteImport.update({
    id: '/sales-call-example',
    path: '/sales-call-example',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingReadAlongRoute =
  DashboardTrainingReadAlongRouteImport.update({
    id: '/read-along',
    path: '/read-along',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingProductKnowledgeRoute =
  DashboardTrainingProductKnowledgeRouteImport.update({
    id: '/product-knowledge',
    path: '/product-knowledge',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingPracticeCallRoute =
  DashboardTrainingPracticeCallRouteImport.update({
    id: '/practice-call',
    path: '/practice-call',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingPlatformRoute =
  DashboardTrainingPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingConsultationVideosRoute =
  DashboardTrainingConsultationVideosRouteImport.update({
    id: '/consultation-videos',
    path: '/consultation-videos',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingAudienceRoute =
  DashboardTrainingAudienceRouteImport.update({
    id: '/audience',
    path: '/audience',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTrainingAiRoute = DashboardTrainingAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardTrainingRoute,
} as any)
const DashboardTrainingSalesFrameworkIndexRoute =
  DashboardTrainingSalesFrameworkIndexRouteImport.update({
    id: '/sales-framework/',
    path: '/sales-framework/',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStripeDepositRoute =
  ApiPublicHooksStripeDepositRouteImport.update({
    id: '/api/public/hooks/stripe-deposit',
    path: '/api/public/hooks/stripe-deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcileCallDurationsRoute =
  ApiPublicHooksReconcileCallDurationsRouteImport.update({
    id: '/api/public/hooks/reconcile-call-durations',
    path: '/api/public/hooks/reconcile-call-durations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/clinic-portal': typeof ClinicPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/booked-appointments': typeof DashboardBookedAppointmentsRoute
  '/clients': typeof DashboardClientsRoute
  '/clinics': typeof DashboardClinicsRoute
  '/inbox': typeof DashboardInboxRoute
  '/leaderboard': typeof DashboardLeaderboardRoute
  '/leads': typeof DashboardLeadsRoute
  '/logs': typeof DashboardLogsRoute
  '/partner-clinics': typeof DashboardPartnerClinicsRoute
  '/pitch-deck': typeof DashboardPitchDeckRoute
  '/sales-call': typeof DashboardSalesCallRoute
  '/sent-links': typeof DashboardSentLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/training': typeof DashboardTrainingRouteWithChildren
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/training/ai': typeof DashboardTrainingAiRoute
  '/training/audience': typeof DashboardTrainingAudienceRoute
  '/training/consultation-videos': typeof DashboardTrainingConsultationVideosRoute
  '/training/platform': typeof DashboardTrainingPlatformRoute
  '/training/practice-call': typeof DashboardTrainingPracticeCallRoute
  '/training/product-knowledge': typeof DashboardTrainingProductKnowledgeRoute
  '/training/read-along': typeof DashboardTrainingReadAlongRoute
  '/training/sales-call-example': typeof DashboardTrainingSalesCallExampleRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/training/': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/reconcile-call-durations': typeof ApiPublicHooksReconcileCallDurationsRoute
  '/api/public/hooks/stripe-deposit': typeof ApiPublicHooksStripeDepositRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/training/sales-framework/': typeof DashboardTrainingSalesFrameworkIndexRoute
}
export interface FileRoutesByTo {
  '/clinic-portal': typeof ClinicPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/booked-appointments': typeof DashboardBookedAppointmentsRoute
  '/clients': typeof DashboardClientsRoute
  '/clinics': typeof DashboardClinicsRoute
  '/inbox': typeof DashboardInboxRoute
  '/leaderboard': typeof DashboardLeaderboardRoute
  '/leads': typeof DashboardLeadsRoute
  '/logs': typeof DashboardLogsRoute
  '/partner-clinics': typeof DashboardPartnerClinicsRoute
  '/pitch-deck': typeof DashboardPitchDeckRoute
  '/sales-call': typeof DashboardSalesCallRoute
  '/sent-links': typeof DashboardSentLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/': typeof DashboardIndexRoute
  '/training/ai': typeof DashboardTrainingAiRoute
  '/training/audience': typeof DashboardTrainingAudienceRoute
  '/training/consultation-videos': typeof DashboardTrainingConsultationVideosRoute
  '/training/platform': typeof DashboardTrainingPlatformRoute
  '/training/practice-call': typeof DashboardTrainingPracticeCallRoute
  '/training/product-knowledge': typeof DashboardTrainingProductKnowledgeRoute
  '/training/read-along': typeof DashboardTrainingReadAlongRoute
  '/training/sales-call-example': typeof DashboardTrainingSalesCallExampleRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/training': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/reconcile-call-durations': typeof ApiPublicHooksReconcileCallDurationsRoute
  '/api/public/hooks/stripe-deposit': typeof ApiPublicHooksStripeDepositRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/training/sales-framework': typeof DashboardTrainingSalesFrameworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/clinic-portal': typeof ClinicPortalRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/booked-appointments': typeof DashboardBookedAppointmentsRoute
  '/_dashboard/clients': typeof DashboardClientsRoute
  '/_dashboard/clinics': typeof DashboardClinicsRoute
  '/_dashboard/inbox': typeof DashboardInboxRoute
  '/_dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/_dashboard/leads': typeof DashboardLeadsRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/partner-clinics': typeof DashboardPartnerClinicsRoute
  '/_dashboard/pitch-deck': typeof DashboardPitchDeckRoute
  '/_dashboard/sales-call': typeof DashboardSalesCallRoute
  '/_dashboard/sent-links': typeof DashboardSentLinksRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/training': typeof DashboardTrainingRouteWithChildren
  '/api/coach-stream': typeof ApiCoachStreamRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/training/ai': typeof DashboardTrainingAiRoute
  '/_dashboard/training/audience': typeof DashboardTrainingAudienceRoute
  '/_dashboard/training/consultation-videos': typeof DashboardTrainingConsultationVideosRoute
  '/_dashboard/training/platform': typeof DashboardTrainingPlatformRoute
  '/_dashboard/training/practice-call': typeof DashboardTrainingPracticeCallRoute
  '/_dashboard/training/product-knowledge': typeof DashboardTrainingProductKnowledgeRoute
  '/_dashboard/training/read-along': typeof DashboardTrainingReadAlongRoute
  '/_dashboard/training/sales-call-example': typeof DashboardTrainingSalesCallExampleRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_dashboard/training/': typeof DashboardTrainingIndexRoute
  '/api/public/hooks/reconcile-call-durations': typeof ApiPublicHooksReconcileCallDurationsRoute
  '/api/public/hooks/stripe-deposit': typeof ApiPublicHooksStripeDepositRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_dashboard/training/sales-framework/': typeof DashboardTrainingSalesFrameworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinic-portal'
    | '/login'
    | '/reset-password'
    | '/thank-you'
    | '/analytics'
    | '/booked-appointments'
    | '/clients'
    | '/clinics'
    | '/inbox'
    | '/leaderboard'
    | '/leads'
    | '/logs'
    | '/partner-clinics'
    | '/pitch-deck'
    | '/sales-call'
    | '/sent-links'
    | '/settings'
    | '/training'
    | '/api/coach-stream'
    | '/email/unsubscribe'
    | '/training/ai'
    | '/training/audience'
    | '/training/consultation-videos'
    | '/training/platform'
    | '/training/practice-call'
    | '/training/product-knowledge'
    | '/training/read-along'
    | '/training/sales-call-example'
    | '/api/public/meta-leads'
    | '/lovable/email/suppression'
    | '/training/'
    | '/api/public/hooks/reconcile-call-durations'
    | '/api/public/hooks/stripe-deposit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/training/sales-framework/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clinic-portal'
    | '/login'
    | '/reset-password'
    | '/thank-you'
    | '/analytics'
    | '/booked-appointments'
    | '/clients'
    | '/clinics'
    | '/inbox'
    | '/leaderboard'
    | '/leads'
    | '/logs'
    | '/partner-clinics'
    | '/pitch-deck'
    | '/sales-call'
    | '/sent-links'
    | '/settings'
    | '/api/coach-stream'
    | '/email/unsubscribe'
    | '/'
    | '/training/ai'
    | '/training/audience'
    | '/training/consultation-videos'
    | '/training/platform'
    | '/training/practice-call'
    | '/training/product-knowledge'
    | '/training/read-along'
    | '/training/sales-call-example'
    | '/api/public/meta-leads'
    | '/lovable/email/suppression'
    | '/training'
    | '/api/public/hooks/reconcile-call-durations'
    | '/api/public/hooks/stripe-deposit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/training/sales-framework'
  id:
    | '__root__'
    | '/_dashboard'
    | '/clinic-portal'
    | '/login'
    | '/reset-password'
    | '/thank-you'
    | '/_dashboard/analytics'
    | '/_dashboard/booked-appointments'
    | '/_dashboard/clients'
    | '/_dashboard/clinics'
    | '/_dashboard/inbox'
    | '/_dashboard/leaderboard'
    | '/_dashboard/leads'
    | '/_dashboard/logs'
    | '/_dashboard/partner-clinics'
    | '/_dashboard/pitch-deck'
    | '/_dashboard/sales-call'
    | '/_dashboard/sent-links'
    | '/_dashboard/settings'
    | '/_dashboard/training'
    | '/api/coach-stream'
    | '/email/unsubscribe'
    | '/_dashboard/'
    | '/_dashboard/training/ai'
    | '/_dashboard/training/audience'
    | '/_dashboard/training/consultation-videos'
    | '/_dashboard/training/platform'
    | '/_dashboard/training/practice-call'
    | '/_dashboard/training/product-knowledge'
    | '/_dashboard/training/read-along'
    | '/_dashboard/training/sales-call-example'
    | '/api/public/meta-leads'
    | '/lovable/email/suppression'
    | '/_dashboard/training/'
    | '/api/public/hooks/reconcile-call-durations'
    | '/api/public/hooks/stripe-deposit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_dashboard/training/sales-framework/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ClinicPortalRoute: typeof ClinicPortalRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiCoachStreamRoute: typeof ApiCoachStreamRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicMetaLeadsRoute: typeof ApiPublicMetaLeadsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksReconcileCallDurationsRoute: typeof ApiPublicHooksReconcileCallDurationsRoute
  ApiPublicHooksStripeDepositRoute: typeof ApiPublicHooksStripeDepositRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-portal': {
      id: '/clinic-portal'
      path: '/clinic-portal'
      fullPath: '/clinic-portal'
      preLoaderRoute: typeof ClinicPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach-stream': {
      id: '/api/coach-stream'
      path: '/api/coach-stream'
      fullPath: '/api/coach-stream'
      preLoaderRoute: typeof ApiCoachStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/training': {
      id: '/_dashboard/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sent-links': {
      id: '/_dashboard/sent-links'
      path: '/sent-links'
      fullPath: '/sent-links'
      preLoaderRoute: typeof DashboardSentLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sales-call': {
      id: '/_dashboard/sales-call'
      path: '/sales-call'
      fullPath: '/sales-call'
      preLoaderRoute: typeof DashboardSalesCallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pitch-deck': {
      id: '/_dashboard/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof DashboardPitchDeckRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/partner-clinics': {
      id: '/_dashboard/partner-clinics'
      path: '/partner-clinics'
      fullPath: '/partner-clinics'
      preLoaderRoute: typeof DashboardPartnerClinicsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads': {
      id: '/_dashboard/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leaderboard': {
      id: '/_dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inbox': {
      id: '/_dashboard/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clinics': {
      id: '/_dashboard/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof DashboardClinicsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/booked-appointments': {
      id: '/_dashboard/booked-appointments'
      path: '/booked-appointments'
      fullPath: '/booked-appointments'
      preLoaderRoute: typeof DashboardBookedAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/training/': {
      id: '/_dashboard/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof DashboardTrainingIndexRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-leads': {
      id: '/api/public/meta-leads'
      path: '/api/public/meta-leads'
      fullPath: '/api/public/meta-leads'
      preLoaderRoute: typeof ApiPublicMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/training/sales-call-example': {
      id: '/_dashboard/training/sales-call-example'
      path: '/sales-call-example'
      fullPath: '/training/sales-call-example'
      preLoaderRoute: typeof DashboardTrainingSalesCallExampleRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/read-along': {
      id: '/_dashboard/training/read-along'
      path: '/read-along'
      fullPath: '/training/read-along'
      preLoaderRoute: typeof DashboardTrainingReadAlongRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/product-knowledge': {
      id: '/_dashboard/training/product-knowledge'
      path: '/product-knowledge'
      fullPath: '/training/product-knowledge'
      preLoaderRoute: typeof DashboardTrainingProductKnowledgeRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/practice-call': {
      id: '/_dashboard/training/practice-call'
      path: '/practice-call'
      fullPath: '/training/practice-call'
      preLoaderRoute: typeof DashboardTrainingPracticeCallRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/platform': {
      id: '/_dashboard/training/platform'
      path: '/platform'
      fullPath: '/training/platform'
      preLoaderRoute: typeof DashboardTrainingPlatformRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/consultation-videos': {
      id: '/_dashboard/training/consultation-videos'
      path: '/consultation-videos'
      fullPath: '/training/consultation-videos'
      preLoaderRoute: typeof DashboardTrainingConsultationVideosRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/audience': {
      id: '/_dashboard/training/audience'
      path: '/audience'
      fullPath: '/training/audience'
      preLoaderRoute: typeof DashboardTrainingAudienceRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/ai': {
      id: '/_dashboard/training/ai'
      path: '/ai'
      fullPath: '/training/ai'
      preLoaderRoute: typeof DashboardTrainingAiRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/_dashboard/training/sales-framework/': {
      id: '/_dashboard/training/sales-framework/'
      path: '/sales-framework'
      fullPath: '/training/sales-framework/'
      preLoaderRoute: typeof DashboardTrainingSalesFrameworkIndexRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe-deposit': {
      id: '/api/public/hooks/stripe-deposit'
      path: '/api/public/hooks/stripe-deposit'
      fullPath: '/api/public/hooks/stripe-deposit'
      preLoaderRoute: typeof ApiPublicHooksStripeDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-call-durations': {
      id: '/api/public/hooks/reconcile-call-durations'
      path: '/api/public/hooks/reconcile-call-durations'
      fullPath: '/api/public/hooks/reconcile-call-durations'
      preLoaderRoute: typeof ApiPublicHooksReconcileCallDurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardTrainingRouteChildren {
  DashboardTrainingAiRoute: typeof DashboardTrainingAiRoute
  DashboardTrainingAudienceRoute: typeof DashboardTrainingAudienceRoute
  DashboardTrainingConsultationVideosRoute: typeof DashboardTrainingConsultationVideosRoute
  DashboardTrainingPlatformRoute: typeof DashboardTrainingPlatformRoute
  DashboardTrainingPracticeCallRoute: typeof DashboardTrainingPracticeCallRoute
  DashboardTrainingProductKnowledgeRoute: typeof DashboardTrainingProductKnowledgeRoute
  DashboardTrainingReadAlongRoute: typeof DashboardTrainingReadAlongRoute
  DashboardTrainingSalesCallExampleRoute: typeof DashboardTrainingSalesCallExampleRoute
  DashboardTrainingIndexRoute: typeof DashboardTrainingIndexRoute
  DashboardTrainingSalesFrameworkIndexRoute: typeof DashboardTrainingSalesFrameworkIndexRoute
}

const DashboardTrainingRouteChildren: DashboardTrainingRouteChildren = {
  DashboardTrainingAiRoute: DashboardTrainingAiRoute,
  DashboardTrainingAudienceRoute: DashboardTrainingAudienceRoute,
  DashboardTrainingConsultationVideosRoute:
    DashboardTrainingConsultationVideosRoute,
  DashboardTrainingPlatformRoute: DashboardTrainingPlatformRoute,
  DashboardTrainingPracticeCallRoute: DashboardTrainingPracticeCallRoute,
  DashboardTrainingProductKnowledgeRoute:
    DashboardTrainingProductKnowledgeRoute,
  DashboardTrainingReadAlongRoute: DashboardTrainingReadAlongRoute,
  DashboardTrainingSalesCallExampleRoute:
    DashboardTrainingSalesCallExampleRoute,
  DashboardTrainingIndexRoute: DashboardTrainingIndexRoute,
  DashboardTrainingSalesFrameworkIndexRoute:
    DashboardTrainingSalesFrameworkIndexRoute,
}

const DashboardTrainingRouteWithChildren =
  DashboardTrainingRoute._addFileChildren(DashboardTrainingRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBookedAppointmentsRoute: typeof DashboardBookedAppointmentsRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardClinicsRoute: typeof DashboardClinicsRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardPartnerClinicsRoute: typeof DashboardPartnerClinicsRoute
  DashboardPitchDeckRoute: typeof DashboardPitchDeckRoute
  DashboardSalesCallRoute: typeof DashboardSalesCallRoute
  DashboardSentLinksRoute: typeof DashboardSentLinksRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrainingRoute: typeof DashboardTrainingRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBookedAppointmentsRoute: DashboardBookedAppointmentsRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardClinicsRoute: DashboardClinicsRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardPartnerClinicsRoute: DashboardPartnerClinicsRoute,
  DashboardPitchDeckRoute: DashboardPitchDeckRoute,
  DashboardSalesCallRoute: DashboardSalesCallRoute,
  DashboardSentLinksRoute: DashboardSentLinksRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrainingRoute: DashboardTrainingRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ClinicPortalRoute: ClinicPortalRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ThankYouRoute: ThankYouRoute,
  ApiCoachStreamRoute: ApiCoachStreamRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicMetaLeadsRoute: ApiPublicMetaLeadsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksReconcileCallDurationsRoute:
    ApiPublicHooksReconcileCallDurationsRoute,
  ApiPublicHooksStripeDepositRoute: ApiPublicHooksStripeDepositRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
