/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardSentLinksRouteImport } from './routes/_dashboard.sent-links'
import { Route as DashboardPitchDeckRouteImport } from './routes/_dashboard.pitch-deck'
import { Route as DashboardLogsRouteImport } from './routes/_dashboard.logs'
import { Route as DashboardLeadsRouteImport } from './routes/_dashboard.leads'
import { Route as DashboardInboxRouteImport } from './routes/_dashboard.inbox'
import { Route as DashboardClinicsRouteImport } from './routes/_dashboard.clinics'
import { Route as DashboardClientsRouteImport } from './routes/_dashboard.clients'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard.analytics'
import { Route as ApiPublicMetaLeadsRouteImport } from './routes/api.public.meta-leads'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSentLinksRoute = DashboardSentLinksRouteImport.update({
  id: '/sent-links',
  path: '/sent-links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPitchDeckRoute = DashboardPitchDeckRouteImport.update({
  id: '/pitch-deck',
  path: '/pitch-deck',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClinicsRoute = DashboardClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicMetaLeadsRoute = ApiPublicMetaLeadsRouteImport.update({
  id: '/api/public/meta-leads',
  path: '/api/public/meta-leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRoute
  '/clinics': typeof DashboardClinicsRoute
  '/inbox': typeof DashboardInboxRoute
  '/leads': typeof DashboardLeadsRoute
  '/logs': typeof DashboardLogsRoute
  '/pitch-deck': typeof DashboardPitchDeckRoute
  '/sent-links': typeof DashboardSentLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/clients': typeof DashboardClientsRoute
  '/clinics': typeof DashboardClinicsRoute
  '/inbox': typeof DashboardInboxRoute
  '/leads': typeof DashboardLeadsRoute
  '/logs': typeof DashboardLogsRoute
  '/pitch-deck': typeof DashboardPitchDeckRoute
  '/sent-links': typeof DashboardSentLinksRoute
  '/settings': typeof DashboardSettingsRoute
  '/': typeof DashboardIndexRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/clients': typeof DashboardClientsRoute
  '/_dashboard/clinics': typeof DashboardClinicsRoute
  '/_dashboard/inbox': typeof DashboardInboxRoute
  '/_dashboard/leads': typeof DashboardLeadsRoute
  '/_dashboard/logs': typeof DashboardLogsRoute
  '/_dashboard/pitch-deck': typeof DashboardPitchDeckRoute
  '/_dashboard/sent-links': typeof DashboardSentLinksRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/api/public/meta-leads': typeof ApiPublicMetaLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/clients'
    | '/clinics'
    | '/inbox'
    | '/leads'
    | '/logs'
    | '/pitch-deck'
    | '/sent-links'
    | '/settings'
    | '/api/public/meta-leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/clients'
    | '/clinics'
    | '/inbox'
    | '/leads'
    | '/logs'
    | '/pitch-deck'
    | '/sent-links'
    | '/settings'
    | '/'
    | '/api/public/meta-leads'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/reset-password'
    | '/_dashboard/analytics'
    | '/_dashboard/clients'
    | '/_dashboard/clinics'
    | '/_dashboard/inbox'
    | '/_dashboard/leads'
    | '/_dashboard/logs'
    | '/_dashboard/pitch-deck'
    | '/_dashboard/sent-links'
    | '/_dashboard/settings'
    | '/_dashboard/'
    | '/api/public/meta-leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicMetaLeadsRoute: typeof ApiPublicMetaLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sent-links': {
      id: '/_dashboard/sent-links'
      path: '/sent-links'
      fullPath: '/sent-links'
      preLoaderRoute: typeof DashboardSentLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/pitch-deck': {
      id: '/_dashboard/pitch-deck'
      path: '/pitch-deck'
      fullPath: '/pitch-deck'
      preLoaderRoute: typeof DashboardPitchDeckRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/logs': {
      id: '/_dashboard/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/leads': {
      id: '/_dashboard/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inbox': {
      id: '/_dashboard/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clinics': {
      id: '/_dashboard/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof DashboardClinicsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/clients': {
      id: '/_dashboard/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/meta-leads': {
      id: '/api/public/meta-leads'
      path: '/api/public/meta-leads'
      fullPath: '/api/public/meta-leads'
      preLoaderRoute: typeof ApiPublicMetaLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardClinicsRoute: typeof DashboardClinicsRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardPitchDeckRoute: typeof DashboardPitchDeckRoute
  DashboardSentLinksRoute: typeof DashboardSentLinksRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardClinicsRoute: DashboardClinicsRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardPitchDeckRoute: DashboardPitchDeckRoute,
  DashboardSentLinksRoute: DashboardSentLinksRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicMetaLeadsRoute: ApiPublicMetaLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
