
create table if not exists public.quiz_questions (
  id uuid primary key default gen_random_uuid(),
  question_no int not null,
  section text not null check (section in ('framework','product','skills','process')),
  question text not null,
  options jsonb not null,
  created_at timestamptz default now()
);

grant select on public.quiz_questions to authenticated;
grant all on public.quiz_questions to service_role;

alter table public.quiz_questions enable row level security;

drop policy if exists "quiz_questions readable" on public.quiz_questions;
create policy "quiz_questions readable" on public.quiz_questions for select to authenticated using (true);

create table if not exists public.rep_quiz_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  passed boolean not null default false,
  best_score int not null default 0,
  attempts int not null default 0,
  passed_at timestamptz,
  updated_at timestamptz default now()
);

grant select, insert, update on public.rep_quiz_progress to authenticated;
grant all on public.rep_quiz_progress to service_role;

alter table public.rep_quiz_progress enable row level security;

drop policy if exists "own quiz progress select" on public.rep_quiz_progress;
drop policy if exists "own quiz progress insert" on public.rep_quiz_progress;
drop policy if exists "own quiz progress update" on public.rep_quiz_progress;

create policy "own quiz progress select" on public.rep_quiz_progress for select to authenticated using (auth.uid() = user_id);
create policy "own quiz progress insert" on public.rep_quiz_progress for insert to authenticated with check (auth.uid() = user_id);
create policy "own quiz progress update" on public.rep_quiz_progress for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

delete from public.quiz_questions;

insert into public.quiz_questions (question_no, section, question, options) values
  (1, 'framework', 'What is the single goal of the Opening?', '[{"text": "Book the appointment in the first 30 seconds", "correct": false}, {"text": "Buy time and get permission to continue without getting hung up on", "correct": true}, {"text": "Give them a price so they stay interested", "correct": false}, {"text": "Qualify them for finance", "correct": false}]'::jsonb),
  (2, 'framework', 'In one line — when does the sale actually happen?', '[{"text": "When you state the price", "correct": false}, {"text": "When you take the $75 deposit", "correct": false}, {"text": "At the audiobook moment, when they emotionally picture their future (the sigh)", "correct": true}, {"text": "When the booking is confirmed", "correct": false}]'::jsonb),
  (3, 'framework', 'A prospect says "I''m busy, can you call me back later?" What do you do?', '[{"text": "Schedule a callback and note the time", "correct": false}, {"text": "Apologise and hang up", "correct": false}, {"text": "Ask for just one minute to see if it even makes sense to call back", "correct": true}, {"text": "Offer to send an email instead", "correct": false}]'::jsonb),
  (4, 'framework', 'Why say the prospect''s name and pause at the very start?', '[{"text": "It fills time while you find your script", "correct": false}, {"text": "It proves you''re not a spam caller and earns an automatic \"good,\" giving you a breath", "correct": true}, {"text": "It''s just good manners", "correct": false}, {"text": "To confirm you dialled the right number", "correct": false}]'::jsonb),
  (5, 'framework', 'What is the MOST important thing to uncover in Discovery?', '[{"text": "Their budget", "correct": false}, {"text": "Which clinic is closest", "correct": false}, {"text": "The \"why now\" — the specific reason they''re acting now", "correct": true}, {"text": "Their email address", "correct": false}]'::jsonb),
  (6, 'framework', 'What is "echoing"?', '[{"text": "Repeating your script word for word", "correct": false}, {"text": "Saying \"okay, got it\" after each answer and moving on", "correct": false}, {"text": "Handing the prospect''s own words back and digging deeper so they feel heard", "correct": true}, {"text": "Speaking louder so they hear you clearly", "correct": false}]'::jsonb),
  (7, 'framework', 'Which of these is a Discovery MISTAKE?', '[{"text": "Asking open questions", "correct": false}, {"text": "Running a rapid-fire checklist (\"okay, and how long? okay, and is it hereditary?\")", "correct": true}, {"text": "Getting the why-now", "correct": false}, {"text": "Asking how it''s affecting them", "correct": false}]'::jsonb),
  (8, 'framework', 'Amplification is best described as:', '[{"text": "Listing all the product''s benefits", "correct": false}, {"text": "Summing up all their pain in one sentence and checking \"is that right?\"", "correct": true}, {"text": "Telling them the price", "correct": false}, {"text": "Painting a picture of their future", "correct": false}]'::jsonb),
  (9, 'framework', 'In Education, what should you do BEFORE explaining the procedure?', '[{"text": "Give the price", "correct": false}, {"text": "Take the deposit", "correct": false}, {"text": "Ask what they already know, then fill the gaps", "correct": true}, {"text": "Book the consult", "correct": false}]'::jsonb),
  (10, 'framework', 'The audiobook moment only works if you:', '[{"text": "Use a generic picture like \"imagine having great hair\"", "correct": false}, {"text": "Keep talking through the silence so it doesn''t get awkward", "correct": false}, {"text": "Mention the price first so they know it''s worth it", "correct": false}, {"text": "Paint a specific picture of their future using their own words/why-now, then go quiet", "correct": true}]'::jsonb),
  (11, 'framework', 'At Commitment, which question is BANNED?', '[{"text": "\"Where are you at with all this?\"", "correct": false}, {"text": "\"Is this something you want to get sorted now?\"", "correct": false}, {"text": "\"Are you just gathering information?\"", "correct": true}, {"text": "\"What''s it been like for you?\"", "correct": false}]'::jsonb),
  (12, 'framework', 'After the sigh lands, what''s the right mindset?', '[{"text": "Start convincing them harder", "correct": false}, {"text": "Presume the yes — it''s a booking, the rest is paperwork", "correct": true}, {"text": "Offer them time to think it over", "correct": false}, {"text": "Re-explain how the procedure works", "correct": false}]'::jsonb),
  (13, 'framework', 'When naming the specialist, you should:', '[{"text": "Say \"one of our doctors will see you\"", "correct": false}, {"text": "Tie the specialist to the prospect''s own words and situation", "correct": true}, {"text": "Avoid naming anyone specific", "correct": false}, {"text": "Let the prospect choose from a list", "correct": false}]'::jsonb),
  (14, 'framework', 'Right after you say "does that sound fair?", you should:', '[{"text": "Keep talking to fill the silence", "correct": false}, {"text": "Offer a discount", "correct": false}, {"text": "Stop and wait for their answer", "correct": true}, {"text": "Move straight to taking payment", "correct": false}]'::jsonb),
  (15, 'framework', 'What''s the correct order of the call?', '[{"text": "Opening, Discovery, Education, Amplification, Audiobook, Price, Commitment, Finance, Deposit", "correct": false}, {"text": "Opening, Discovery, Amplification, Education, Audiobook, Commitment, Price & Specialist, Finance, Deposit & Book", "correct": true}, {"text": "Discovery, Opening, Amplification, Education, Price, Audiobook, Deposit", "correct": false}, {"text": "Opening, Education, Discovery, Price, Audiobook, Commitment, Deposit", "correct": false}]'::jsonb),
  (16, 'framework', 'The why-now answer "it''s just been on my mind lately" should be treated as:', '[{"text": "The complete answer — move on", "correct": false}, {"text": "The surface — keep digging for the specific event behind it", "correct": true}, {"text": "A sign they''re not serious", "correct": false}, {"text": "A reason to give the price", "correct": false}]'::jsonb),
  (17, 'product', 'Where are the grafts taken from in a hair transplant?', '[{"text": "A separate donor person", "correct": false}, {"text": "The back and sides — the permanent zone", "correct": true}, {"text": "Synthetic fibres", "correct": false}, {"text": "The thinning area on top", "correct": false}]'::jsonb),
  (18, 'product', 'Why does transplanted hair keep growing and not fall out?', '[{"text": "It''s held in with a special adhesive", "correct": false}, {"text": "It''s topped up every year", "correct": false}, {"text": "It comes from the permanent zone and is genetically resistant to balding", "correct": true}, {"text": "It''s treated with ongoing medication", "correct": false}]'::jsonb),
  (19, 'product', 'Is transplanted hair real?', '[{"text": "No, it''s synthetic", "correct": false}, {"text": "It''s a partial wig", "correct": false}, {"text": "It''s donor hair from someone else", "correct": false}, {"text": "Yes — it''s the person''s own real hair; they can cut, wash and style it", "correct": true}]'::jsonb),
  (20, 'product', 'What is the single biggest factor in whether a transplant looks natural?', '[{"text": "The colour match", "correct": false}, {"text": "The angle and direction each graft is placed at, matching natural growth", "correct": true}, {"text": "The number of grafts used", "correct": false}, {"text": "The reputation of the clinic", "correct": false}]'::jsonb),
  (21, 'product', 'What does the Norwood scale measure?', '[{"text": "Hair thickness", "correct": false}, {"text": "The stage/pattern of male hair loss", "correct": true}, {"text": "The cost of the procedure", "correct": false}, {"text": "How long results last", "correct": false}]'::jsonb),
  (22, 'product', 'What is the "donor clock"?', '[{"text": "How long the procedure takes on the day", "correct": false}, {"text": "The booking system for appointments", "correct": false}, {"text": "The idea that donor hair is finite and the balding area keeps spreading, so acting sooner is better", "correct": true}, {"text": "A finance repayment schedule", "correct": false}]'::jsonb),
  (23, 'product', 'The garden analogy for a transplant is best described as:', '[{"text": "Planting seeds and waiting for them to grow", "correct": false}, {"text": "Moving healthy grass (back and sides) onto bare dirt (top), with only so much grass to move", "correct": true}, {"text": "Watering the lawn every day", "correct": false}, {"text": "Laying brand-new turf over everything", "correct": false}]'::jsonb),
  (24, 'product', 'The procedure is typically done:', '[{"text": "Under general anaesthetic with an overnight hospital stay", "correct": false}, {"text": "Under local anaesthetic (numbing), same day, home that night", "correct": true}, {"text": "With no anaesthetic at all", "correct": false}, {"text": "Over several days in hospital", "correct": false}]'::jsonb),
  (25, 'product', 'A prospect worries it''ll "look fake, like plugs." The best response is to:', '[{"text": "Say \"you''ll be right, don''t worry about it\"", "correct": false}, {"text": "Agree that it can look pretty fake", "correct": false}, {"text": "Change the subject to price", "correct": false}, {"text": "Acknowledge it, explain the old plug look is decades old, that today individual follicles are placed at the natural angle so even a barber can''t tell, and offer before/after photos", "correct": true}]'::jsonb),
  (26, 'product', 'Why send before/after photos during the call?', '[{"text": "To fill time", "correct": false}, {"text": "Show-don''t-tell — photos are concrete proof, far more convincing than words", "correct": true}, {"text": "Only because the prospect asked", "correct": false}, {"text": "To collect their phone number", "correct": false}]'::jsonb),
  (27, 'product', '"My mate got one in Turkey for three grand." This is best understood as:', '[{"text": "A reason to end the call", "correct": false}, {"text": "Proof they''ll never buy locally", "correct": false}, {"text": "A common market belief to acknowledge, then differentiate on quality and who''s doing the work", "correct": true}, {"text": "Completely irrelevant", "correct": false}]'::jsonb),
  (28, 'product', 'What largely determines whether someone is a good candidate?', '[{"text": "Their age alone", "correct": false}, {"text": "Their income", "correct": false}, {"text": "Their donor hair — its supply and density", "correct": true}, {"text": "Their postcode", "correct": false}]'::jsonb),
  (29, 'skills', 'On the call, you should come across as a:', '[{"text": "An order-taker waiting for easy buyers", "correct": false}, {"text": "An advisor — not a telemarketer", "correct": true}, {"text": "A hard, aggressive closer", "correct": false}, {"text": "A mate having a casual chat", "correct": false}]'::jsonb),
  (30, 'skills', 'In early discovery, the ideal talk ratio is roughly:', '[{"text": "Rep 70%, prospect 30%", "correct": false}, {"text": "Prospect ~70%, rep ~30%", "correct": true}, {"text": "50/50", "correct": false}, {"text": "Rep does nearly all the talking", "correct": false}]'::jsonb),
  (31, 'skills', 'An early "I''m not interested" is best understood as:', '[{"text": "A final, genuine no", "correct": false}, {"text": "A reflex — it doesn''t mean anything yet", "correct": true}, {"text": "A formal complaint", "correct": false}, {"text": "A reason to hang up", "correct": false}]'::jsonb),
  (32, 'skills', 'The correct FIRST move with any objection is to:', '[{"text": "Argue your point firmly", "correct": false}, {"text": "Agree / never fight it", "correct": true}, {"text": "Offer a discount", "correct": false}, {"text": "End the call politely", "correct": false}]'::jsonb),
  (33, 'skills', 'People mostly make big buying decisions based on:', '[{"text": "Logic and careful comparison", "correct": false}, {"text": "Emotion first, then they justify it with logic", "correct": true}, {"text": "Price alone", "correct": false}, {"text": "Whatever''s quickest", "correct": false}]'::jsonb),
  (34, 'skills', 'Why is silence (the pause) important?', '[{"text": "It''s awkward and should be filled quickly", "correct": false}, {"text": "It signals you''re nervous", "correct": false}, {"text": "It does the work — after a question or \"sound fair?\", you let them answer", "correct": true}, {"text": "It just wastes the prospect''s time", "correct": false}]'::jsonb),
  (35, 'skills', 'Consistent results come from:', '[{"text": "Being in a good mood that day", "correct": false}, {"text": "Following the framework every call, not relying on energy", "correct": true}, {"text": "Talking quickly to cover more ground", "correct": false}, {"text": "Good luck with the leads", "correct": false}]'::jsonb),
  (36, 'skills', 'What''s genuinely the worst thing that happens if you ask for the booking and they say no?', '[{"text": "You get in serious trouble", "correct": false}, {"text": "Nothing — they say no, you both move on, and it sharpens you for the next call", "correct": true}, {"text": "You lose the lead forever and it''s your fault", "correct": false}, {"text": "The clinic complains about you", "correct": false}]'::jsonb),
  (37, 'process', 'What are you actually booking the prospect into on the call?', '[{"text": "The surgery itself", "correct": false}, {"text": "A consultation — assessment, hair design and imaging", "correct": true}, {"text": "A follow-up phone call", "correct": false}, {"text": "A finance application only", "correct": false}]'::jsonb),
  (38, 'process', 'The consult deposit is:', '[{"text": "$395 and non-refundable", "correct": false}, {"text": "$1,000 upfront", "correct": false}, {"text": "$75, refunded when they arrive — a commitment device to make sure they show", "correct": true}, {"text": "Free, with no deposit at all", "correct": false}]'::jsonb),
  (39, 'process', 'When a prospect asks the procedure price, you should:', '[{"text": "Refuse to discuss price at all", "correct": false}, {"text": "Give an exact, final quote on the spot", "correct": false}, {"text": "Avoid the question and change the subject", "correct": false}, {"text": "Give a rough range (with finance) after gauging them, framing the exact figure as what the assessment determines", "correct": true}]'::jsonb),
  (40, 'process', 'A prospect says "I''ll need to think about it / talk to my wife." Best response:', '[{"text": "Pressure them to decide right now", "correct": false}, {"text": "Agree it''s a big decision, re-anchor to what mattered to them, and route to the free no-commitment consult", "correct": true}, {"text": "End the call and follow up next week", "correct": false}, {"text": "Offer them a discount to decide today", "correct": false}]'::jsonb);
