-- Deployment receipt: invoice schema applied through Lovable on 2026-10-04.
-- The schema is defined by 20261004090000_rep_invoices.sql.
-- Keep this recorded migration version without replaying duplicate CREATE statements.
-- The connected deployment created the private bucket through the storage API.
