-- Deployment history marker: Lovable applied the already-reviewed reminder SQL
-- to the existing production schema under this generated UTC timestamp.
-- Keep this version for history reconciliation. Fresh databases must apply the
-- canonical copies below in dependency order (roles before linked reminders):
--   20261003000000_consultation_and_procedure_roles.sql
--   20261003010000_link_and_safe_patient_reminders.sql
-- Repeating the reminder SQL here would reference role columns before they exist.
